Repository yiisoft/db-migration, pull requests merged in 2020-09, with the labels that each got.

#44 Tests for migration class
  phpunit.xml.dist
  tests/Migration.php
  tests/MigrationTest.php
  tests/TestCase.php
Labels: status:code review, type:test

#45 Fix tests.
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  composer.json
  config/common.php
  config/console.php
  config/params.php
  config/tests.php
  psalm.xml
  src/Command/CreateCommand.php
  src/Helper/ConsoleHelper.php
  src/Migration.php
  src/Service/Database/ListTablesService.php
  src/Service/Generate/CreateService.php
  src/Service/MigrationService.php
  tests/Data/.gitignore
  tests/MigrationTest.php
  tests/Paths/CreateTableCommandTest.php
  tests/TestCase.php
Labels: status:ready for merge, type:test

#46 Fix baseDir package directory migration.
  src/Helper/ConsoleHelper.php
Labels: status:code review

#47 More improvements.
  .phan/config.php
  README.md
  phpunit.xml.dist
  src/Command/CreateCommand.php
  src/Command/DownCommand.php
  src/Command/HistoryCommand.php
  src/Command/NewCommand.php
  src/Command/RedoCommand.php
  src/Command/UpdateCommand.php
  src/Migration.php
  src/Service/Generate/CreateService.php
  src/Service/MigrationService.php
Labels: status:code review

#48 Fix psalm issues.
  src/Helper/ConsoleHelper.php
  src/Service/Database/ListTablesService.php
Labels: status:code review
