Repository yiisoft/db-migration, pull requests merged in 2021-01, with the labels that each got.

#79 Fix error on create table with string column definitions
  src/Migration.php
  tests/src/BaseTest.php
  tests/src/MigrationTest.php
Labels: status:code review, type:bug

#77 Use View::class for console.
  config/params.php
  src/Service/Generate/CreateService.php
  tests/src/BaseTest.php
Labels: status:ready for merge

#81 Add methods truncateTable, renameTable, addColumn, dropColumn to MigrationBuilder
  src/MigrationBuilder.php
  tests/src/MigrationBuilderTest.php
Labels: status:code review

#80 Move prepare db to migration from MigrationBuilder to MigrationService
  composer.json
  src/MigrationBuilder.php
  src/Service/MigrationService.php
Labels: status:code review

#83 Refactoring + Remove base migration
  config/console.php
  src/Command/CreateCommand.php
  src/Command/DownCommand.php
  src/Command/HistoryCommand.php
  src/Command/RedoCommand.php
  src/Command/UpdateCommand.php
  src/Informer/ConsoleMigrationInformer.php
  src/Informer/MigrationInformerInterface.php
  src/Informer/NullMigrationInformer.php
  src/MigrationBuilder.php
  src/Migrator.php
  src/Service/Database/ListTablesService.php
  src/Service/Migrate/DownService.php
  src/Service/Migrate/UpdateService.php
  src/Service/MigrationService.php
  tests/src/BaseTest.php
  tests/src/Command/Namespaces/UpdateCommandTest.php
  tests/src/Command/Paths/UpdateCommandTest.php
  tests/src/MigrationBuilderTest.php
  tests/src/Service/Migrate/DownServiceTest.php
  tests/src/Service/Migrate/UpdateServiceTest.php
  tests/src/Service/MigrationServiceTest.php
  tests/src/StubMigrationInformer.php
Labels: status:code review

#84 Change default migration name
  src/Command/CreateCommand.php
Labels: status:code review
