Repository yiisoft/db-migration, pull requests merged in 2023-12, with the labels that each got.

#245 Fix #239: Add usage with Symfony app
  README.md
  docs/en/usage-standalone.md
  docs/en/usage-with-symfony.md
  docs/en/usage-with-yii-console.md
Labels: type:docs

#246 Improve console utility
  bin/MigrationContainer.php
  bin/yii-db-migration
  bin/yii-db-migration.bat
  bin/yii-db-migration.php
  composer.json
  docs/en/usage-standalone.md
  phpunit.xml.dist
  psalm.xml
  tests/Migration/BinTest.php
  tests/Migration/bin-runner.php
Labels: status:code review

#248 Remove aliases
  .github/workflows/build.yml
  .github/workflows/composer-require-checker.yml
  .github/workflows/mariadb.yml
  .github/workflows/mssql.yml
  .github/workflows/mysql.yml
  .github/workflows/oracle.yml
  .github/workflows/pgsql.yml
  .github/workflows/rector.yml
  .github/workflows/sqlite.yml
  .github/workflows/static.yml
  bin/yii-db-migration
  composer.json
  docs/en/usage-with-symfony.md
  src/Service/Generate/CreateService.php
  src/Service/MigrationService.php
  tests/Common/Command/AbstractCreateCommandTest.php
  tests/Common/Command/AbstractNewCommandTest.php
  tests/Common/Command/AbstractUpdateCommandTest.php
  tests/Migration/Service/MigrationServiceTest.php
  tests/Support/Factory/MssqlFactory.php
  tests/Support/Factory/MysqlFactory.php
  tests/Support/Factory/OracleFactory.php
  tests/Support/Factory/PostgreSqlFactory.php
  tests/Support/Factory/SqLiteFactory.php
  tests/Support/Helper/ContainerHelper.php
  tests/Support/Helper/MigrationHelper.php
Labels: status:code review

#250 Fix #227
  .github/workflows/bc.yml
  CHANGELOG.md
  src/AbstractMigrationBuilder.php
  tests/Common/AbstractMigrationBuilderTest.php
Labels: type:enhancement, status:code review
